// Mocks generated by Mockito 5.4.2 from annotations
// in clean_architecture_tdd_course/test/features/number_trivia/presentation/bloc/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:Enter/core/error/failures.dart' as _i6;
import 'package:Enter/core/util/input_converter.dart' as _i8;
import 'package:Enter/features/card_management/domain/entities/user_data.dart'
    as _i7;
import 'package:Enter/features/card_management/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:Enter/features/card_management/domain/usecases/get_auth_data.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAuthToken].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAuthToken extends _i1.Mock implements _i4.GetAuthData {
  MockGetAuthToken() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserData>> call(_i4.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.UserData>>.value(
            _FakeEither_1<_i6.Failure, _i7.UserData>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserData>>);
}

/// A class which mocks [InputEmailValidation].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputEmailValidation extends _i1.Mock
    implements _i8.InputEmailValidation {
  MockInputEmailValidation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Either<_i6.Failure, String> emailValidator(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #emailValidator,
          [email],
        ),
        returnValue: _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #emailValidator,
            [email],
          ),
        ),
      ) as _i3.Either<_i6.Failure, String>);
}

/// A class which mocks [InputPasswordValidation].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputPasswordValidation extends _i1.Mock
    implements _i8.InputPasswordValidation {
  MockInputPasswordValidation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Either<_i6.Failure, String> passwordValidator(String? password) =>
      (super.noSuchMethod(
        Invocation.method(
          #passwordValidator,
          [password],
        ),
        returnValue: _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #passwordValidator,
            [password],
          ),
        ),
      ) as _i3.Either<_i6.Failure, String>);
}
