name: Goodbytz 
description: TDD Clean architecture technical test

version: 1.0.0+1

environment:
  sdk: '>=2.20.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.6.0
  # Bloc for state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programming
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker_plus: ^2.0.0
  http: ^1.1.0
  # Local cache
  flutter_secure_storage: ^8.0.0
  # UI
  sizer: ^2.0.15
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  # Test
  bloc_test: ^9.1.3
  # IO
  universal_io: ^2.2.2
  

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/