// Mocks generated by Mockito 5.4.2 from annotations
// in clean_architecture_tdd_course/test/features/number_trivia/data/repositories/repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_architecture_tdd_course/core/network/network_info.dart'
    as _i6;
import 'package:clean_architecture_tdd_course/features/card_management/data/datasources/local_data_source.dart'
    as _i5;
import 'package:clean_architecture_tdd_course/features/card_management/data/datasources/remote_data_source.dart'
    as _i3;
import 'package:clean_architecture_tdd_course/features/card_management/data/models/user_data_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserAuthModel_0 extends _i1.SmartFake implements _i2.UserDataModel {
  _FakeUserAuthModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i3.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserDataModel> getAuthToken(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthToken,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.UserDataModel>.value(_FakeUserAuthModel_0(
          this,
          Invocation.method(
            #getAuthToken,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.UserDataModel>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i5.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserDataModel> getCredentials() => (super.noSuchMethod(
        Invocation.method(
          #getCachedAuthToken,
          [],
        ),
        returnValue: _i4.Future<_i2.UserDataModel>.value(_FakeUserAuthModel_0(
          this,
          Invocation.method(
            #getCachedAuthToken,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserDataModel>);
  @override
  _i4.Future<void> cacheCards(_i2.UserDataModel? tokenToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAuthToken,
          [tokenToCache],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
